### ISSUE TITLE
Center bottom bar icons

### ISSUE THREAD

**Issue by zanhk** [Elisha-Misoi/Nomadic#22]
This is a great clone, but do you have idea how to fully get the result with the bottom bar menu without title and with vertically centered icons?

**Comment by ElishaMisoi** [comment]
> This is a great clone, but do you have idea how to fully get the result with the bottom bar menu without title and with vertically centered icons?

Hello, thanks for checking out this sample. Currently the way Shell has been designed, there's no way to accomplish that, not unless you use some form of custom renderer.

But if you'd like to ditch Shell, you can use these plugins:

1. [Sharpnado.Presentation.Forms](https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/roubachof/Sharpnado.Presentation.Forms/wiki/Pure-Xamarin.Forms-tabs&ved=2ahUKEwiSq5yn3e3pAhVHx4UKHWF_BYkQFjAAegQIARAB&usg=AOvVaw0VUWn9NyqHa5QdAOcUwEOC)

2. [SFTabView](https://help.syncfusion.com/xamarin/tabbed-view/getting-started)

**Comment by zanhk** [comment]
Thanks for the info
